version: '3'
services:
  database:
    build:
      context: ./
      dockerfile: Dockerfile-ohdb
      args:
        OH_DB_LANG: ${OH_DB_LANG}
    image: oh-core_database:latest
    ports:
      - "${OH_MARIADB_PORT}:3306"
    environment:
      MYSQL_DATABASE: ${OH_MARIADB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${OH_MARIADB_ROOT_PASSWORD}
      MYSQL_USER: ${OH_MARIADB_USER}
      MYSQL_PASSWORD: ${OH_MARIADB_PASSWORD}

    # This ensures the server starts with local_infile=1
    command: mysqld --local-infile=1 --lower_case_table_names=1 --explicit_defaults_for_timestamp=OFF
    # Mount our custom config file so that both server and client settings
    # are applied (particularly [client] local_infile=1).
    volumes:
      - ./my.cnf:/etc/mysql/conf.d/my.cnf